// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Anchors: typeof import('./src/components/Anchors.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    CompClients: typeof import('./src/components/CompClients.vue')['default']
    CompFinancials: typeof import('./src/components/CompFinancials.vue')['default']
    CompHistory: typeof import('./src/components/CompHistory.vue')['default']
    CompHoldings: typeof import('./src/components/CompHoldings.vue')['default']
    CompInfo: typeof import('./src/components/CompInfo.vue')['default']
    CompLitigations: typeof import('./src/components/CompLitigations.vue')['default']
    CompPeers: typeof import('./src/components/CompPeers.vue')['default']
    CompProperties: typeof import('./src/components/CompProperties.vue')['default']
    CompSwot: typeof import('./src/components/CompSwot.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    IpoInfo: typeof import('./src/components/IpoInfo.vue')['default']
    IpoObjects: typeof import('./src/components/IpoObjects.vue')['default']
    Promoters: typeof import('./src/components/Promoters.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Topbar: typeof import('./src/components/Topbar.vue')['default']
  }
}
